### ISSUE TITLE
Power Outage Checklist 

### ISSUE THREAD

**Issue by spruceboy** [gina-alaska/sandy-project#12]
**At 7pm - Jay will:**

**Incoming data turn off -**
- [ ] bigdog
- [ ] relaymonkey
- [ ] sandydog

**VM and machines turned off**
- [ ] Fake Orville off
- [ ] NRT VMS off.  
- [ ] turn off feeder2-dds.x.gina.alaska.edu
- [ ] turn off feeder2.x.gina.alaska.edu
- [ ] turn off feeder-ingest2.x.gina.alaska.edu

**on restore**

- [ ] check landfall vms
- [ ] check db vms
- [ ] check dashboards
- [ ] turn on data from bigdog
- [ ] turn on data from relaymonkey
- [ ] turn on data from sandydog
- [ ] check NRT VMS  
- [ ] check feeder2-dds.x.gina.alaska.edu
- [ ] check feeder2.x.gina.alaska.edu
- [ ] check feeder-ingest2.x.gina.alaska.edu
- [ ] check Orville
- [ ] check ftp server
- [ ] check ldm server

**Notes:** 
Turn off nrt vms - VM: 
`knife ssh --no-host-key-verify 'name:nrt*'  'sudo poweroff' `

Knife status pre-shutdown:
`(base) [jecable@roundrect ~]$ knife status | grep nrt
20183 hours ago, nrt-jay-test.x.gina.alaska.edu, centos 6.9.
10379 hours ago, nrt-rtstps-test-8115.x.gina.alaska.edu, centos 6.9.
10379 hours ago, nrt-rtstps-prod-7b4b.x.gina.alaska.edu, centos 6.8.
10366 hours ago, nrt-seadas-prod-1c53.x.gina.alaska.edu, centos 6.8.
10057 hours ago, nrt-csppsdr-test-b701.x.gina.alaska.edu, centos 7.4.1708.
10057 hours ago, nrt-cspp-extras-test-a701.x.gina.alaska.edu, centos 7.5.1804.
10034 hours ago, nrt-rtstps-prod-39c9.x.gina.alaska.edu, centos 6.8.
8905 hours ago, nrt-aapp-test-a875.x.gina.alaska.edu, centos 6.10.
4878 hours ago, nrt-cloud-prod.x.gina.alaska.edu, centos 7.7.1908.
1883 hours ago, nrt-cloud-prod-02.x.gina.alaska.edu, centos 7.7.1908.
1883 hours ago, nrt-csppsdr-prod-bea0.x.gina.alaska.edu, centos 6.8.
31 minutes ago, nrt-polar2grid-test-cdd1.x.gina.alaska.edu, centos 6.10.
30 minutes ago, nrt-cloud-test-01.x.gina.alaska.edu, centos 7.6.1810.
30 minutes ago, nrt-csppsdr-prod-0003.x.gina.alaska.edu, centos 7.6.1810.
30 minutes ago, nrt-seadas-test-74de.x.gina.alaska.edu, centos 6.9.
29 minutes ago, nrt-dds-prod-01b1.x.gina.alaska.edu, centos 6.8.
29 minutes ago, nrt-redis-prod-3282.x.gina.alaska.edu, centos 6.8.
28 minutes ago, nrt-csppedr-test-1723.x.gina.alaska.edu, centos 6.9.
28 minutes ago, nrt-aapp-prod-22b6.x.gina.alaska.edu, centos 6.9.
27 minutes ago, nrt-cspp-extras-prod-0004.x.gina.alaska.edu, centos 7.6.1810.
26 minutes ago, nrt-cloud-prod-03.x.gina.alaska.edu, centos 7.7.1908.
26 minutes ago, nrt-ldm-prod-ad7d.gina.alaska.edu, centos 6.10.
25 minutes ago, nrt-ldmworker-prod-556c.x.gina.alaska.edu, centos 6.8.
24 minutes ago, nrt-aapp-prod-0002.x.gina.alaska.edu, centos 7.6.1810.
24 minutes ago, nrt-cspp-extras-test-a700.x.gina.alaska.edu, centos 7.4.1708.
21 minutes ago, nrt-landfall-prod-cb9f.x.gina.alaska.edu, centos 6.8.
17 minutes ago, nrt-cspp-extras-prod-0001.x.gina.alaska.edu, centos 7.5.1804.
17 minutes ago, nrt-polar2grid-prod-0004.x.gina.alaska.edu, centos 7.8.2003.
16 minutes ago, nrt-noaaavhrr-prod-755d.x.gina.alaska.edu, centos 6.10.
15 minutes ago, nrt-polar2grid-prod-ddf3.x.gina.alaska.edu, centos 6.10.
14 minutes ago, nrt-polar2grid-prod-0003.x.gina.alaska.edu, centos 7.6.1810.
12 minutes ago, nrt-geotiff-test-1445.x.gina.alaska.edu, centos 6.9.
12 minutes ago, nrt-csppsdr-prod-fafb.x.gina.alaska.edu, centos 6.8.
11 minutes ago, nrt-landfall-test-cd6c.x.gina.alaska.edu, centos 6.9.
10 minutes ago, nrt-cspp-extras-prod-0003.x.gina.alaska.edu, centos 7.6.1810.
10 minutes ago, nrt-ldm-test-50bf.x.gina.alaska.edu, centos 6.9.
7 minutes ago, nrt-csppsdr-test-ef45.x.gina.alaska.edu, centos 6.9.
7 minutes ago, nrt-dashboard-prod-6d25.x.gina.alaska.edu, centos 6.8.
6 minutes ago, nrt-cloud-prod-01.x.gina.alaska.edu, centos 7.7.1908.
5 minutes ago, nrt-geotiff-prod-358c.x.gina.alaska.edu, centos 6.9.
5 minutes ago, nrt-dashboard-test-2609.x.gina.alaska.edu, centos 6.9.
5 minutes ago, nrt-geotiff-prod-cd98.x.gina.alaska.edu, centos 6.9.
4 minutes ago, nrt-ldmworker-test-9150.x.gina.alaska.edu, centos 6.9.
4 minutes ago, nrt-polar2grid-prod-5c84.x.gina.alaska.edu, centos 6.9.
3 minutes ago, nrt-redis-test-2232.x.gina.alaska.edu, centos 6.9.
1 minute  ago, nrt-dds-test, centos 6.10.
1 minute  ago, nrt-csppedr-prod-44f2.x.gina.alaska.edu, centos 6.8.
1 minute  ago, nrt-database-prod-27f0.x.gina.alaska.edu, centos 6.8.
1 minute  ago, nrt-cspp-extras-prod-0002.x.gina.alaska.edu, centos 7.6.1810.
30 seconds ago, nrt-database-test-baa4.x.gina.alaska.edu, centos 6.9.
`
